### ISSUE TITLE
Feature request: Remove internal branches from coverage report

### ISSUE THREAD

**Issue by nlohmann** [RPGillespie6/fastcov#6] opened 2019-04-06 06:39 UTC
#### My issue

Using fastcov with [nlohmann/json](https://github.com/nlohmann/json) works now, thanks a lot! However, I am still depending on a second tool to filter the lcov file before rendering HTML which is [`filterbr.py`](https://github.com/gsauthof/imapdl/blob/master/ci/filterbr.py) to remove branches that are displayed in the output, but are somewhere under the hood inside the STL. Examples are assertions or `throw` statements where the report always complains that the branch "after" the code is not executed:

Before using the filter tool:

<img width="871" alt="Screen Shot 2019-04-06 at 08 35 17" src="https://user-images.githubusercontent.com/159488/55665903-11703780-5847-11e9-81cd-86a60e3ef3b4.png">

After using the filter tool:

<img width="871" alt="Screen Shot 2019-04-06 at 08 37 06" src="https://user-images.githubusercontent.com/159488/55665910-2d73d900-5847-11e9-839c-673d39d15895.png">

The problem is briefly described on [StackOverflow](https://stackoverflow.com/questions/42003783/lcov-gcov-branch-coverage-with-c-producing-branches-all-over-the-place/43726240#43726240).

#### Feature request

Offer the functionality of the `filterbr.py` tool in fastcov. Then fastcov would be the single tool required to manage coverage information.

**Comment by RPGillespie6** [comment] 2019-04-06 14:15
I may be able to handle this elegantly since gcov9 labels whether a given branch is "exceptional" or not (currently fastcov is ignoring this information). If this is the case I could simply provide an option to filter exceptional branches. (https://gcc.gnu.org/onlinedocs/gcc.pdf - see p. 852).

It's possible gcov doesn't consider all of these branches "exceptional" though, in which case I could either add support for `LCOV_EXCL_BR_LINE` (http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php) to clean up any stragglers, or, (if gcov9 exceptional branch filtering doesn't pan out at all), scan for conditional statements like `filterbr.py` is doing (though it looks like `filterbr.py` only looks for `if` statements and doesn't consider ternary statements.

I'll run a few experiments and see if I can fix this sometime next week.

**Comment by RPGillespie6** [comment] 2019-04-07 04:30
Ok, I ran a few experiments. Filtering based on gcov9's exceptional branch labeling works marvelously and is extremely fast and simple. I'm going to make this  filtering enabled by default for branch coverage. If you decide later you want those exceptional branches, you can re-enable with `--exceptional-branch-coverage`.

However, there is one slight problem. This does not remove _all_ undesirable branches - in this case, it does not remove `assert` branches since `assert` does not `throw` under the hood, but rather calls `abort()`.

Therefore, I have provided 2 options to mitigate this:

1. You can include the flag `--exclude-assert-branches` which, while scanning for exclusion markers, will also scan for `assert` statements

2. You can include `//LCOV_EXCL_BR_LINE` on any line you don't want branch coverage for, including `assert`.

Current implementation is on [a branch](https://github.com/RPGillespie6/fastcov/tree/bpg/exceptional_branch_filtering) and I believe it is working. However, I will test against `json` on Monday and compare directly against `filterbr.py`.

Note this implementation is not exactly like `filterbr.py` and may cause your branch coverage to appear to drop if there are, for example, ternary statements in your code that `filterbr.py` was previously removing but are now being included.

**Comment by nlohmann** [comment] 2019-04-07 05:35
Very good!

**Comment by RPGillespie6** [comment] 2019-04-08 18:47
Ok, I have pushed this feature to master.

You should see a significant increase in branch reporting for things like ternary expressions, loop conditionals, switch statements, etc.

There is one problem that's difficult to solve though, and that's how to determine which branches were generated by gcc and which were branches in the original code. For now I am tossing out all branch coverage for a given line if _any_ of the branches on that line are exceptional ones.

This causes a loss in branch reporting for conditionals that have exceptional code embedded in them, for example, `json_pointer.hpp:750` contains exceptional branches generated by gcc for the use of the `[]` operator on strings.

Currently the best option is to refactor so the exceptional branches are outside of the `if` statement. Alternatively, I could remove _just_ exceptional branches from coverage report, but it seems as though GCC sometimes injects *more* than just exceptional branches (which are also unreachable). However, I will continue to study this and possibly see if @marxin has any suggestions on how to distinguish developer branches from gcc-injected branches. 

Note you'll need to add one new flag to the fastcov invocation: `--exclude-assert-branches`

**Comment by RPGillespie6** [comment] 2019-04-09 01:21
I guess it depends on if you prefer false positives or false negatives. I could make it so it removes just exceptional branches from the line, leaving the other ones, but you might have some noisy non-exceptional, but gcc-injected branches showing up.

**Comment by RPGillespie6** [comment] 2019-04-09 17:00
I have a StackOverflow question about it [here](https://stackoverflow.com/questions/55597684/aggregate-initialization-branch-coverage), but it seems that aggregate initialization causes GCC to produce non-exceptional branch noise that I can detect and remove.

I'm going to try implement aggregate initialization filtering by default in addition to exceptional branch filtering and see if we get the best of all worlds.

**Comment by marxin** [comment] 2019-04-10 11:39
> Currently the best option is to refactor so the exceptional branches are outside of the `if` statement. Alternatively, I could remove _just_ exceptional branches from coverage report, but it seems as though GCC sometimes injects _more_ than just exceptional branches (which are also unreachable) for things like initializer lists. However, I will continue to study this and possibly see if @marxin has any suggestions on how to distinguish developer branches from gcc-injected branches.

Please provide me couple of examples of GCC injected branches which are not a typical C++ exception code. I can then play with that.

**Comment by RPGillespie6** [comment] 2019-04-10 13:57
It seems that aggregate initialization causes GCC to generate not just exceptional branches, but also unreachable non-exceptional branches. Here is a code sample: https://stackoverflow.com/questions/55597684/aggregate-initialization-branch-coverage

**Comment by marxin** [comment] 2019-04-11 08:26
I can confirm that, with C++, exceptions and all the deallocation one has more complicated control flow graph. For simplified test-case:

```
#include <vector>
#include <string>

using namespace std;

struct A {
   vector<string> reference_tokens;
};

int main() {
  A a;

  vector<string> rt = {"a"};
  a.reference_tokens = {rt[0]};
  return 0;
}
```

we have following GIMPLE:

```
main ()
{
  const struct basic_string * D.29581;
  const struct basic_string * D.29565;
  struct vector rt;
  struct A a;
  int D.33840;
  const struct basic_string D.29580[1];
  struct initializer_list D.33836;
  struct allocator_type D.29577;
  struct allocator D.29562;
  const struct basic_string D.29564[1];
  struct initializer_list D.33832;
  struct value_type & _1;
  const struct basic_string * _2;
  const struct basic_string * _3;
  const struct basic_string * _4;
  const struct basic_string * _5;
  const struct basic_string * _23;
  const struct basic_string * _24;
  const struct basic_string * _34;
  const struct basic_string * _35;
  int _38;
  const struct basic_string * _43;
  const struct basic_string * _44;
  const struct basic_string * _50;
  const struct basic_string * _51;

  <bb 2> :
  A::A (&a);
  std::allocator<char>::allocator (&D.29562);
  std::__cxx11::basic_string<char>::basic_string (&D.29564[0], "a", &D.29562);

  <bb 3> :
  D.33832._M_array = &D.29564;
  D.33832._M_len = 1;
  std::allocator<std::__cxx11::basic_string<char> >::allocator (&D.29577);
  std::vector<std::__cxx11::basic_string<char> >::vector (&rt, D.33832, &D.29577);

  <bb 4> :
  std::allocator<std::__cxx11::basic_string<char> >::~allocator (&D.29577);
  D.29577 ={v} {CLOBBER};
  _23 = &D.29564 + 32;

  <bb 5> :
  # _2 = PHI <_23(4), _24(6)>
  if (&D.29564 == _2)
    goto <bb 7>; [INV]
  else
    goto <bb 6>; [INV]

  <bb 6> :
  _24 = _2 + 18446744073709551584;
  std::__cxx11::basic_string<char>::~basic_string (_24);
  goto <bb 5>; [INV]

  <bb 7> :
  D.29564 ={v} {CLOBBER};
  std::allocator<char>::~allocator (&D.29562);
  D.29562 ={v} {CLOBBER};
  _1 = std::vector<std::__cxx11::basic_string<char> >::operator[] (&rt, 0);
  std::__cxx11::basic_string<char>::basic_string (&D.29580[0], _1);

  <bb 8> :
  D.33836._M_array = &D.29580;
  D.33836._M_len = 1;
  std::vector<std::__cxx11::basic_string<char> >::operator= (&a.reference_tokens, D.33836);

  <bb 9> :
  _34 = &D.29580 + 32;

  <bb 10> :
  # _4 = PHI <_34(9), _35(11)>
  if (&D.29580 == _4)
    goto <bb 12>; [INV]
  else
    goto <bb 11>; [INV]

  <bb 11> :
  _35 = _4 + 18446744073709551584;
  std::__cxx11::basic_string<char>::~basic_string (_35);
  goto <bb 10>; [INV]

  <bb 12> :
  D.29580 ={v} {CLOBBER};
  _38 = 0;
  std::vector<std::__cxx11::basic_string<char> >::~vector (&rt);
  A::~A (&a);
  a ={v} {CLOBBER};
  rt ={v} {CLOBBER};

  <bb 13> :
<L9>:
  return _38;

  <bb 14> :
<L10>:
  std::allocator<std::__cxx11::basic_string<char> >::~allocator (&D.29577);
  resx 8

  <bb 15> :
<L11>:
  D.29577 ={v} {CLOBBER};
  resx 7

  <bb 16> :
<L12>:
  _50 = &D.29564 + 32;

  <bb 17> :
  # _3 = PHI <_50(16), _51(18)>
  if (&D.29564 == _3)
    goto <bb 19>; [INV]
  else
    goto <bb 18>; [INV]

  <bb 18> :
  _51 = _3 + 18446744073709551584;
  std::__cxx11::basic_string<char>::~basic_string (_51);
  goto <bb 17>; [INV]

  <bb 19> :
  resx 6

  <bb 20> :
<L16>:
  D.29564 ={v} {CLOBBER};
  resx 5

  <bb 21> :
<L17>:
  std::allocator<char>::~allocator (&D.29562);
  resx 4

  <bb 22> :
<L18>:
  D.29562 ={v} {CLOBBER};
  resx 3

  <bb 23> :
<L19>:
  _43 = &D.29580 + 32;

  <bb 24> :
  # _5 = PHI <_43(23), _44(25)>
  if (&D.29580 == _5)
    goto <bb 26>; [INV]
  else
    goto <bb 25>; [INV]

  <bb 25> :
  _44 = _5 + 18446744073709551584;
  std::__cxx11::basic_string<char>::~basic_string (_44);
  goto <bb 24>; [INV]

  <bb 26> :
  resx 20

  <bb 27> :
<L23>:
  D.29580 ={v} {CLOBBER};
  resx 19

  <bb 28> :
<L24>:
  std::vector<std::__cxx11::basic_string<char> >::~vector (&rt);
  resx 18

  <bb 29> :
<L25>:
  A::~A (&a);
  resx 2

  <bb 30> :
<L26>:
  a ={v} {CLOBBER};
  rt ={v} {CLOBBER};
  resx 1

}
```

**Comment by RPGillespie6** [comment] 2019-04-11 22:42
For now, I've made `fastcov` try to detect initializer list branch noise and remove it by default. Perhaps someday we can have a perfect solution to removing GCC-injected branches, but I think for now this gets pretty close.

I've removed the flag `--exclude-assert-branches` in favor of a more generic one. You can now pass `--exclude-br-lines-starting-with` and exclude branch coverage from any lines starting with the listed keywords. In the case of `json`, you'll probably want to pass `--exclude-br-lines-starting-with assert return` (not sure if you care about return conditional branches).

**Comment by marxin** [comment] 2019-04-12 13:22
I can probably return to it and make mark better branches that are artificial (and different from `except`).

**Comment by RPGillespie6** [comment] 2019-04-12 13:41
That would be ideal - if gcov could mark artificial branches so that they can be filtered out since most developers are going to regard them as noise. I don't mind if artificial branches are a superset of exceptional branches either (i.e. a branch that has both `throw` true and `artificial` true) - it would actually simplify fastcov since then I can just filter *all* artificial branches, leaving only the original branches the developer introduced.

I imagine that task is non-trivial though - determining whether a branch is "artificial" or not could be very difficult depending on how GCC was designed (initializer lists aren't the only case where artificial branches are being generated).

**Comment by marxin** [comment] 2019-05-17 08:09
So for the test-case in https://github.com/RPGillespie6/fastcov/issues/6#issuecomment-482019123 we end up with:

```
                    "branches": [
                        {
                            "count": 1,
                            "dst": 14,
                            "fallthrough": true,
                            "src": 13,
                            "throw": false
                        },
                        {
                            "count": 0,
                            "dst": 38,
                            "fallthrough": false,
                            "src": 13,
                            "throw": true
                        },
                        {
                            "count": 1,
                            "dst": 15,
                            "fallthrough": true,
                            "src": 14,
                            "throw": false
                        },
                        {
                            "count": 0,
                            "dst": 33,
                            "fallthrough": false,
                            "src": 14,
                            "throw": true
                        },
                        {
                            "count": 1,
                            "dst": 17,
                            "fallthrough": true,
                            "src": 16,
                            "throw": false
                        },
                        {
                            "count": 1,
                            "dst": 18,
                            "fallthrough": false,
                            "src": 16,
                            "throw": false
                        },
                        {
                            "count": 0,
                            "dst": 35,
                            "fallthrough": true,
                            "src": 34,
                            "throw": false
                        },
                        {
                            "count": 0,
                            "dst": 36,
                            "fallthrough": false,
                            "src": 34,
                            "throw": false
                        }
                    ],
                    "count": 2,
                    "function_name": "main",
                    "line_number": 14,
                    "unexecuted_block": false
```

as seen I added some extra `src` and `dst` fields. It identifies basic block ID, which is:

```
  <bb 16> :
  # _4 = PHI <_34(15), _35(17)>
  if (&D.29697 == _4)
    goto <bb 18>; [INV]
  else
    goto <bb 17>; [INV]

  <bb 17> :
  _35 = _4 + 18446744073709551584;
  std::__cxx11::basic_string<char>::~basic_string (_35);
  goto <bb 16>; [INV]

  <bb 18> :
  D.29697 ={v} {CLOBBER};
  _38 = 0;
  std::vector<std::__cxx11::basic_string<char> >::~vector (&rt);
```

As you can see the control flow is not about an exceptional edges. But about a checking of allocation status which then conditional leads to a deallocation. That said, I don't see an easy way how to mark "artificial" edges and languages like C++ have a complication allocation or object constructor calls.

**Comment by RPGillespie6** [comment] 2019-05-22 18:54
Thanks, marxin, I'll mess around with `src` and `dest` fields to see if I can tune out any more noise. I recognize it's a hard problem to solve.

**Comment by RPGillespie6** [comment] 2019-06-11 17:09
@nlohmann Sorry this took so long. I was trying to find a generic way to de-noise branch coverage, but it doesn't seem like there is an easy way to do so short of turning fastcov into a machine learning science project! 

Back to your original request, I added the following option (since [476b9e](https://github.com/RPGillespie6/fastcov/commit/476b9e2118ef1eed4b1dfd532f68546e6f183340)) `--include-br-lines-starting-with` which tells fastcov to _only_ include branches from source lines that start with one of the provided strings.

If you pass the following: `--exceptional-branch-coverage --include-br-lines-starting-with if else` to fastcov, it will produce a report that is identical to the one produced using `filterbr.py` with the exception of multi-line if statements. It looks like there is only one spot in your code where this happens though: `binary_writer.hpp:370-391`.

Is this good enough to close the issue? Or do you prefer fastcov lexically parse the source looking for start and end parenthesis like `filterbr.py` does?

I tried to make the branch filtering options generic enough that you can whitelist or blacklist the types of statements you are interested in seeing branch coverage for. These options are `--include-br-lines-starting-with` and `--exclude-br-lines-starting-with`. The implementation is very fast, simple, and flexible but has the drawback of not capturing multi-line conditionals.

You could work around this though by doing something like:

```
    if    (j.m_value.number_integer >= (std::numeric_limits<std::int8_t>::min)() and
    /*br*/ j.m_value.number_integer <= (std::numeric_limits<std::int8_t>::max)())
```

and then passing `--exceptional-branch-coverage --include-br-lines-starting-with if else /*br*/`

**Comment by RPGillespie6** [comment] 2019-08-06 22:33
I'm going to close this issue. I can re-open if there is still functionality that needs to be added, but I think the latest version should have everything needed to resolve this!

**Closed by RPGillespie6** 2019-08-06 22:33 UTC
