### ISSUE TITLE
Support for Sonarqube generic test data XML output?

### ISSUE THREAD

**Issue by f18m** [RPGillespie6/fastcov#60] opened 2020-12-15 13:25 UTC
Hi,

great program thanks for this contribution. I integrated it without any issue in a few projects. However regarding coverage it's nice to have a standardized way to report it to 3rd party tool (e.g. code quality analyzers and bots that populate the differential code coverage in each MR)... I wonder: is there any plan to add support for Cobertura XML output to fastcov?
That would allow integration with a bunch of other tools...

Thanks!

**Comment by RPGillespie6** [comment] 2020-12-15 14:18
Duplicate of #35. Currently the solution is to chain the output of fastcov to https://github.com/eriwen/lcov-to-cobertura-xml. I did not plan on adding cobertura XML output to native fastcov since lcov-to-cobertura-xml seems to work well and it's one less thing for me to maintain. If there was enough demand and a good reason to add this output directly to fastcov I would consider it I suppose.

**Comment by f18m** [comment] 2020-12-15 14:39
> Duplicate of #35. Currently the solution is to chain the output of fastcov to https://github.com/eriwen/lcov-to-cobertura-xml. I did not plan on adding cobertura XML output to native fastcov since lcov-to-cobertura-xml seems to work well and it's one less thing for me to maintain. If there was enough demand and a good reason to add this output directly to fastcov I would consider it I suppose.

Ok good to know, thanks. It's just that the lcov-to-cobertura-xml project seems unmaintained/dead by looking at the activity logs... anyway I will try it out and check - I hope it works with Python3.7 :)

Thanks

**Comment by RPGillespie6** [comment] 2020-12-15 14:43
If lcov-to-cobertura-xml is dead/doesn't work with python3 that would probably be a good enough reason to add it to fastcov. If that's the case let me know (I don't use cobertura xml so I haven't tested it myself but other users have said it works well in the past)

**Comment by rburtnykx** [comment] 2020-12-17 15:42
Hi ,

I can prove that lcov-to-cobertura-xml works with python3 as we use it in cooperation with fastcov

**Comment by f18m** [comment] 2020-12-17 21:29
Yeah I confirm it works - I tried today and it worked fine even though I just discovered that Sonarqube (my final target for code coverage results) apparently does not like Cobertura XML for C/C++ code. Rather it takes either .gcov directly or its own XML format (that gcovr seems to support but not fastcov)

**Comment by RPGillespie6** [comment] 2020-12-17 22:50
Correct, fastcov does not currently support sonarqube format. Please change the title of this issue to indicate a request for Sonarqube XML support. I believe this is the format that would need to be generated: https://docs.sonarqube.org/latest/analysis/generic-test/

Fastcov native format is JSON so it wouldn't be too hard to write a python script that iterates through the JSON and generates XML of that format. I haven't decided yet if I want to integrate it directly into fastcov or create a separate `fastcov-to-sonarcube.py` (for example). I'm leaning towards the latter since cobertura XML is currently a separate script.

**Comment by f18m** [comment] 2020-12-17 22:58
> Correct, fastcov does not currently support sonarqube format. Please change the title of this issue to indicate a request for Sonarqube XML support. I believe this is the format that would need to be generated: https://docs.sonarqube.org/latest/analysis/generic-test/

yes, correct!

> Fastcov native format is JSON so it wouldn't be too hard to write a python script that iterates through the JSON and generates XML of that format. I haven't decided yet if I want to integrate it directly into fastcov or create a separate `fastcov-to-sonarcube.py` (for example). I'm leaning towards the latter since cobertura XML is currently a separate script.

ok I see - I guess it would not be hard right - just it's not clear to me all the topic of covered/uncovered branches and how gcov handles them :)

**Comment by RPGillespie6** [comment] 2020-12-23 18:11
I'd encourage you to take a look at fastcov JSON output (i.e. just generate a native fastcov json report). It should be pretty self descriptive in the JSON what lines/branches of each file are covered. You can then spin through it with a second python script and convert to sonarcube xml and open a PR for it. If you want I can give you a skeleton python script to do so. 

I could also implement it myself, but it would have to be next week during the holiday break and I wouldn't be able to test it very well since I don't have sonarqube.

**Comment by RPGillespie6** [comment] 2020-12-31 03:10
Okay, I created a utility that converts fastcov json to sonarqube xml. You can grab it here:

https://github.com/RPGillespie6/fastcov/blob/fastcov_utils/utils/fastcov_to_sonarqube.py

Please let me know if this fixes the issue.

You can invoke with, i.e.

```
$ ./fastcov_to_sonarqube.py coverage.json -o sonarcube_coverage.xml --pretty
```

(or leave off `--pretty` if you want it minified)

**Comment by f18m** [comment] 2020-12-31 15:20
Thanks  a lot @RPGillespie6 !! 
I will try out the conversion script ASAP and will report back here!

**Comment by f18m** [comment] 2021-01-01 21:42
Hi @RPGillespie6 ,
I tested the conversion script and I think it works. However I'm hitting a problem with my Sonarqube installation where Sonarqube will fail the "CLI scan" phase with an error about the "build wrapper output" missing despite I'm providing it.
I'm investigating the reasons why this happen.

Anyway the XML I provided seems to be processed just fine, so thanks again!

**Closed** 2021-01-09 18:11 UTC
